#!/bin/bash

source /usr/lib/openfoam/openfoam2112/etc/bashrc

echo $1 $2 $3 $4 $5 $6

echo surfaceTransformPoints -rotate-angle \'\(\(0.000188 0.0540462 0.0029555\) $1\)\' $2 $3 > output.txt
echo surfaceTransformPoints -rotate-angle \'\(\(0.000188 0.0540462 0.0029555\) $4\)\' $5 $6 > output.txt
#
surfaceTransformPoints -rotate-angle \'\(\(0.000188 0.0540462 0.0029555\) $1\)\' $2 $3
surfaceTransformPoints -rotate-angle \'\(\(0.000188 0.0540462 0.0029555\) $4\)\' $5 $6